package domain;

/**
 * Códigos de erro de validação e processamento
 */
public enum Erro {
	CPF_INVALIDO,
	NOME_INVALIDO,
	DATA_INVALIDA,
	CLIENTE_MENOR_DE_IDADE,
	CPF_JA_EXISTENTE,
	LOGRADOURO_INVALIDO,
	NUMERO_INVALIDO,
	COMPLEMENTO_INVALIDO,
	BAIRRO_INVALIDO,
	CIDADE_INVALIDA,
	CEP_INVALIDO,
	UF_INVALIDA,
	DDD_INVALIDO,
	NUMERO_TEL_INVALIDO,
	ENDERECO_INVALIDO,
	TELEFONE_INVALIDO,
	ERRO_BD,
	PLACA_INVALIDA,
	PLACA_REPETIDA,
	MODELO_INVALIDO,
	DIARIA_VALOR_INVALIDO,
	ANO_FABRICACAO_INVALIDO,
	QUILOMETRAGEM_INVALIDA,
	CLIENTE_INEXISTENTE,
	PLACA_INEXISTENTE, 
	VEICULO_JA_ALOCADO
}
